M48
; DRILL file {KiCad (7.0.0)} date Sun Nov  5 00:37:02 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-05T00:37:02+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
%
G90
G05
T1
X6.4138Y-3.824
X6.4138Y-3.928
X6.4138Y-4.032
X6.4138Y-4.136
T0
M30
